---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ze.
--- DateTime: 2021/3/13 0:41
---

function (self, unitId, unitFrame, envTable, modTable)
    --insert code here
    --timeIntervals
    local minute, hour, day = 60, 3600, 86400
    local aboutMinute, aboutHour, aboutDay = 59.5, 60 * 59.5, 3600 * 23.5

    local function round(x) return floor(x + 0.5) end

    function Plater.FormatTime(seconds)
        if seconds < 10 then
            return "%.1f", seconds
        elseif seconds < aboutMinute then
            local seconds = round(seconds)
            return seconds ~= 0 and seconds or ""
        elseif seconds < aboutHour then
            return "%dm", round(seconds / minute)
        elseif seconds < aboutDay then
            return "%dh", round(seconds / hour)
        else
            return "%dd", round(seconds / day)
        end
    end

    envTable.getColorByTime = function(current, max)
        if max == 0 then max = 1 end
        local percentage = (current / max) * 100
        local red, green = 0, 0
        if percentage >= 50 then
            --green to yellow
            green        = 1
            red            = ((100 - percentage) / 100) * 2
        else
            --yellow to red
            red    = 1
            green        = ((100 - (100 - percentage)) / 100) * 2
        end
        return red, green, 0
    end
end